# Generated by Django 5.0.13 on 2025-03-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_college_acceptance_rate_college_average_fin_aid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='ten_year_earnings',
            new_name='yearly_earnings',
        ),
    ]
